### ISSUE TITLE
hide方法报空指针异常

### ISSUE THREAD

**Issue by 1042933551** [qstumn/BadgeView#1]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View, android.view.ViewGroup$LayoutParams)' on a null object reference

QBadgeView.screenFromWindow(QBadgeView.java:227)

我使用setVisibility(View.GONE);来代替hide

**Comment by qstumn** [comment]
您好，请不要用setVisibility(View.GONE);来代替hide，无论是hide方法还是setBadgeNumber(0)都是按照不在canvas上绘制任何内容的方式达到的隐藏，setVisibility(View.GONE)可能会导致拖拽消除或者带动画隐藏操作出现问题

**Comment by 1042933551** [comment]
但是hide空指针

**Comment by qstumn** [comment]
你是不是在onResume之前调用hide(true)了？

**Comment by 1042933551** [comment]
是的,我测试一下hide方法能不能用(onCreate方法中)，然后就报空指针

**Comment by qstumn** [comment]
动画方式隐藏会先把view添加到Activity的DecorView里，DecorView我是在onAttachedToWindow的时候赋值的，所以是会报空指针，谢谢您的反馈意见

**Comment by 1042933551** [comment]
所以hide方法需要在onResume方法中执行对吗

**Comment by qstumn** [comment]
已更新1.0.3版本，已修复这个问题

**Comment by imliujun** [comment]
![image](https://cloud.githubusercontent.com/assets/9779970/24197988/e3fe27d8-0f3e-11e7-8ef2-e6e52173cf40.png)
1.0.6版本出现的，最新的1.1.0版本还没测，但是我看相关代码并没有改动，应该也有这个问题

**Comment by qstumn** [comment]
1.1.0应该已经解决此问题，现在文字在没有测量之前是不会绘制的
