### ISSUE TITLE
还是有很多问题的。

### ISSUE THREAD

**Issue by cv0cv0** [qstumn/BadgeView#10]
比如阴影消失，RadioGroup中的RadioButton失效，相对布局和约束布局offset是反的。

**Comment by qstumn** [comment]
是的，RadioGroup中的RadioButton失效是肯定的，可以不用RadioGroup自己控制RadioButton的Check状态。
请问你这里阴影消失是在什么情况下出现的呢？
offsetX和offsetY是相对gravity而言的，就比如Start|Top中offsetX就是向右偏移，offsetY向下偏移，在End|Bottom中正好相反

**Comment by cv0cv0** [comment]
我遇到的问题是我在radiogroup中使用了阴影属性，然后把radiogroup设为目标view，阴影就消失了，所以我又在radiogroup外面套了一层cardview。

**Comment by qstumn** [comment]
你说的阴影是5.0以上的translationZ效果么

**Comment by cv0cv0** [comment]
差不多，我用的是elevation。

**Comment by qstumn** [comment]
的确是会失效，因为此时radiogroup的父view大小是和radiogroup一样大的，elevation或者translationZ效果都不能在这种情况下生效，这的确没有考虑到，暂时无法解决此问题
