### ISSUE TITLE
拖拽消失的范围有点小

### ISSUE THREAD

**Issue by ppg408331701** [qstumn/BadgeView#12]
QQ上的似乎可拖动的范围比可视范围大,BadgeView则似乎比较小,拖几次才能消除

**Comment by qstumn** [comment]
你的意思是指手指按不到么，触发不了拖动？还是？

**Comment by ppg408331701** [comment]
手指不容易按到,触发不了拖动
和QQ对比,QQ比较容易按到那个滑动区域

**Comment by qstumn** [comment]
这个按到的位置判断是严格按照当前角标的形状范围来判断的，你可能是差一点没点到里面
QQ的的确是超出范围也能点到，我觉的范围广了也不是太好，有可能会影响TargetView的点击事件，位置判断是在QBadgeView源码onTouchEvent方法179行，你可以按照自己的想要的方式进行修改

**Comment by ppg408331701** [comment]
恩谢谢了,我自己改改
