### ISSUE TITLE
横竖屏切换时

### ISSUE THREAD

**Issue by ljy0662** [qstumn/BadgeView#13]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fly.market/com.fly.market.activity.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.HorizontalScrollView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/app_tab_bottom. Make sure other views do not use the same id.

是不是copy相同ID 的VIew 问题？

**Comment by qstumn** [comment]
我横竖屏切换时无论加不加android:configChanges都没有出现这种情况，你是在什么情况下发生的呢?
