### ISSUE TITLE
setBadgeNumber（0）时不隐藏

### ISSUE THREAD

**Issue by look0089** [qstumn/BadgeView#17]
我在onResume方法中调用

    public void setMessageNum() {
        AppLog.redLog("sk", "MsgNum:" + Constant.MESNUM);
        MsgBadge = new QBadgeView(getActivity()).bindTarget(img_message).setGravityOffset(0, -3, true).setShowShadow(false).setBadgeNumber(Constant.MESNUM);
    }

日志打印  E/sk: MsgNum:0

但是没有隐藏badge

**Comment by look0089** [comment]
看了一下是自己的问题，onResume是用new的 导致原来的那个依然显示。。

**Comment by weiaiming** [comment]
> 看了一下是自己的问题，onResume是用new的 导致原来的那个依然显示。。

谢谢，看了你的解答 我也解决了。非常感谢
