### ISSUE TITLE
设置居中方式无效

### ISSUE THREAD

**Issue by liangjingkanji** [qstumn/BadgeView#18]
TOP直接不显示了. 只有CENTER有效. 默认的是在图片的左边居中. 
我是给imageView设置的

**Comment by liangjingkanji** [comment]
我看了demo也不知道是怎么放到右上角的, 是图片大小刚好才行???

**Comment by qstumn** [comment]
可否贴出你的代码看看

**Comment by XWS** [comment]
![image](https://cloud.githubusercontent.com/assets/16014068/24231962/904739ac-0fc2-11e7-8555-ef2af8a9b0c2.png)
设置位置无效

**Comment by qstumn** [comment]
@XWS 你好，你能描述一下怎么无效了么，默认的位置就是end | top在右上角，你这样写其实和没写是一样的

**Comment by XWS** [comment]
@qstumn 你好， 我昨天用textview的时候发现是可以设置dot的位置的，但是用imageview的时候我发现，设置这两个属性，dot的位置还是在左下角，位置并没有发生变化。

**Comment by qstumn** [comment]
我用imageview是没有任何问题的，包括demo里也有结合imageview的例子，在DataBinding里使用也没有出问题，你能把你的完整代码贴出来看看么，不方便在这贴，可以发我邮箱
qstumn@163.com

**Comment by XWS** [comment]
@qstumn 我尽量复现吧，因为我自己写了一个。

**Comment by XWS** [comment]
@qstumn 
![w 7_2 _ njo _x xhv1e10k](https://cloud.githubusercontent.com/assets/16014068/24278109/abf6b118-107c-11e7-957a-1d67be964fde.png)

**Comment by XWS** [comment]
![53 ykdny9v98i6v fm gh8](https://cloud.githubusercontent.com/assets/16014068/24278127/ca47195a-107c-11e7-88e5-7c2d4d401d67.png)

**Comment by XWS** [comment]
![screenshot_2017-03-24-10-30-26](https://cloud.githubusercontent.com/assets/16014068/24278205/506c584c-107d-11e7-863c-35a48d71f0ae.png)

**Comment by qstumn** [comment]
你这个其实就是在右上角，但是为什么看起来不在右上角呢，因为Badge默认是有外边距的，并不是紧贴边缘，你可以把外边距去掉试一试

**Comment by XWS** [comment]
好的，我试试
