### ISSUE TITLE
如果是放在recyclerview里面的控件，通过更新item, 因为复用，会有点问题。

### ISSUE THREAD

**Issue by yxyaxng** [qstumn/BadgeView#19]
if(badge==null){
                badge = new QBadgeView(context).bindTarget(img_type);
                badge.setBadgeGravity(Gravity.END | Gravity.TOP);
                badge.setGravityOffset(DensityUtil.dip2px(context,6), DensityUtil.dip2px(context,6), false);
                badge.setBadgePadding(3, true);
                badge.setBadgeTextSize(10, true);
                badge.setBadgeTextColor(context.getResources().getColor(R.color.mine_secretary_color));
                badge.setBadgeBackgroundColor(Color.parseColor("#ffffff"));
            }
            badge.setBadgeNumber(typeBean.getMesCount());

**Comment by qstumn** [comment]
你可以参照我demo中RecyclerViewActivity中的用法，你这种写法不太好

**Comment by clunyes** [comment]
q.rorbin.badgeview.QBadgeView$BadgeContainer cannot be cast to android.widget.ImageView，不能放recycleview中用

**Comment by qstumn** [comment]
请参照此处解决此问题 https://github.com/qstumn/BadgeView#5一些注意事项
