### ISSUE TITLE
关于radiogroup中radiobutton添加角标的问题

### ISSUE THREAD

**Issue by gaoshan12312** [qstumn/BadgeView#20]
radiogroup中radiobutton添加角标，貌似那个radiobutton的互斥事件就失效了。这应该是radiobutton的parentview也就是radiogroup被替换了的原因吧，怎么处理这个问题呢？

**Comment by qstumn** [comment]
很抱歉，暂不支持绑定RadioButton，RadioButton的Parent必须是RadioGroup，一旦换掉就会出现你描述的情况了

**Comment by gaoshan12312** [comment]
好的，谢谢

**Comment by CoolCsf** [comment]
你好，我的RadioButton的Parent是radioGroup。但是还是会有相同的问题
