### ISSUE TITLE
能否添加只显示小红点,不显示具体数字的属性

### ISSUE THREAD

**Issue by jianfeng318** [qstumn/BadgeView#21]
作者您好,这个库写的很好,可以省去了自己写拖拽的代码!,希望作者添加只显示小红点,不显示具体数字的属性?如微信的发现按钮,谢谢!

**Comment by qstumn** [comment]
您好，本身就有此功能，setBadgeNumber传负数即可

**Comment by jianfeng318** [comment]
好的,谢谢提醒
