### ISSUE TITLE
显示位置问题

### ISSUE THREAD

**Issue by 18710891669** [qstumn/BadgeView#22]
new QBadgeView(mActivity).bindTarget(imageView).setBadgeNumber(5).setBadgeGravity(Gravity.END | Gravity.TOP);
我用的是Gravity.END | Gravity.TOP  显示在imageView右上角   运行起来是在左下角？这个还需要其他设置吗

**Comment by qstumn** [comment]
https://github.com/qstumn/BadgeView/issues/18
是不是和这个问题一样
