### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by xyy465925800** [qstumn/BadgeView#25]
绑定radiobutton 后点击事件失效

**Comment by qstumn** [comment]
能详细描述下么

**Comment by KookCaptain** [comment]
new QBadgeView(this).bindTarget(tarView)之后 这个控件设置的点击事件就会失效

**Comment by 872102569** [comment]
可以在bindTarget(tarView)之后，再给radiobutton设置点击事件。。我是这样解决的

**Comment by ALguojian** [comment]
这个问题解决了嘛。我试了在bindTarget(tarView之后在设置点击事件，还是不行，绑定红点之后的那个radiobutton点击效果就失效了

**Comment by 872102569** [comment]
我是这样实现的，为每个RadioButton设置点击事件
`RadioGroup radioGroup = (RadioGroup) findViewById(R.id.radio_group);
        //三个RadioButton
        final RadioButton rb_a = (RadioButton) findViewById(R.id.a);
        final RadioButton rb_b = (RadioButton) findViewById(R.id.b);
        final RadioButton rb_c = (RadioButton) findViewById(R.id.c);
        new QBadgeView(this).bindTarget(rb_a).setBadgeNumber(28).setGravityOffset(1, 1, true);//设置角标
        //为每个RadioButton设置点击事件
        rb_a.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                rb_a.setChecked(true);
                rb_b.setChecked(false);
                rb_c.setChecked(false);
            }
        });
        rb_b.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                rb_a.setChecked(false);
                rb_b.setChecked(true);
                rb_c.setChecked(false);
            }
        });
        rb_c.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                rb_a.setChecked(false);
                rb_b.setChecked(false);
                rb_c.setChecked(true);
            }
        });`

**Comment by 872102569** [comment]
我是这样做的
//三个RadioButton
        final RadioButton rb_a = (RadioButton) findViewById(R.id.a);
        final RadioButton rb_b = (RadioButton) findViewById(R.id.b);
        final RadioButton rb_c = (RadioButton) findViewById(R.id.c);
        new QBadgeView(this).bindTarget(rb_a).setBadgeNumber(28).setGravityOffset(1, 1, true);//设置角标
        //为每个RadioButton设置点击事件
        rb_a.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                rb_a.setChecked(true);
                rb_b.setChecked(false);
                rb_c.setChecked(false);
            }
        });
        rb_b.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                rb_a.setChecked(false);
                rb_b.setChecked(true);
                rb_c.setChecked(false);
            }
        });
        rb_c.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                rb_a.setChecked(false);
                rb_b.setChecked(false);
                rb_c.setChecked(true);
            }
        });

**Comment by cjjwzj** [comment]
我也是这个问题

**Comment by five-And** [comment]
修改下源码这个地方 

final BadgeContainer badgeContainer = new BadgeContainer(getContext());
                badgeContainer.setId(targetView.getId());
//                targetView.setId(View.NO_ID);
                targetView.setId(targetView.getId());



可以改下这个地方啊,  原本事件能响应的, 只不过根据把Id 设置成-1 后, 就找不到要响应的case ,
把view Id 设置回去就好了

**Comment by cjjwzj** [comment]
楼上方法还没试 等下去看看,我是用匿名内部类解决的, setonclicklistener(这里)用 new就可以,用this就不行

**Comment by ClareChen** [comment]
应该是 @five-And 说的原因。并且那行代码是1.1.2版本新加的，不清楚作者为什么要做这个修改。

**Comment by kevenshao** [comment]
mCartImg.setOnClickListener(this);
mBadge = new QBadgeView(this).bindTarget(mCartImg).setBadgeNumber(0);
//目前QBadgeView有bug,需重新设置一次id，否则无法响应点击事件
mCartImg.setId(R.id.cart_img);

**Comment by happyCoding12138** [comment]
```
radiobution.setOnClickListener(new OnClickListener(){
    public void `onClick(View v){`
        radiogroup.click(radiobutton的id);
    }
});
```

**Comment by happyCoding12138** [comment]
设置radiobutton的点击事件，点击的时候，设置radiogroup选中的id为当前radiobutton的id
```
radiobution.setOnClickListener(new OnClickListener(){
    public void onClick(View v){
        radiogroup.click(radiobutton的id);
    }
});
```

**Comment by qstumn** [comment]
就是five-And 说的问题，1.1.3已经改回来了，实在不好意思，最近几个月忙疯了一直都没有改

**Comment by tx123456** [comment]
我已经升级到了1.1.3,这个问题还是存在啊
