### ISSUE TITLE
不能设置？Gravity.END | Gravity.CENTER

### ISSUE THREAD

**Issue by SheepYang1993** [qstumn/BadgeView#3]
不能设置？Gravity.END | Gravity.CENTER；
only support Gravity.START | Gravity.TOP , Gravity.END | Gravity.TOP , Gravity.START | Gravity.BOTTOM , Gravity.END | Gravity.BOTTOM , Gravity.CENTER？

**Comment by qstumn** [comment]
您好，暂时只支持only support Gravity.START | Gravity.TOP , Gravity.END | Gravity.TOP , Gravity.START | Gravity.BOTTOM , Gravity.END | Gravity.BOTTOM , Gravity.CENTER
计划下个版本加入更多的位置支持
