### ISSUE TITLE
出现以下bug

### ISSUE THREAD

**Issue by jtsky** [qstumn/BadgeView#31]
``java.lang.RuntimeException:Unable to start activity ComponentInfo{com.twl.qichechaoren_business/com.twl.qichechaoren_business.purchase.view.PurchaseManageActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.CompoundButton$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rb_cart. Make sure other views do not use the same id.

**Comment by qstumn** [comment]
可以详细描述在什么情况下出现的这个异常么

**Comment by imgod1** [comment]
https://github.com/qstumn/BadgeView/issues/43
