### ISSUE TITLE
在fragment里面不显示

### ISSUE THREAD

**Issue by china-coder** [qstumn/BadgeView#33]
在fragment里面创建，使用的是textview，但是就是不显示效果，在activity里面构建是显示的

**Comment by qstumn** [comment]
可以详细描述下贴下fragment的代码么，我经常在fragment中使用没有遇到问题

**Comment by china-coder** [comment]
`  public void changeMessageNumber(TextView tv, int nubmer) {
        new QBadgeView((AppApplication.getInstance())).bindTarget(tv).setBadgeNumber(10);
    }`

**Comment by china-coder** [comment]
`  @ViewInject(R.id.tv_haha)
    TextView tv_haha;`

**Comment by china-coder** [comment]
在fragment里面的onCreateView 调用 changeMessageNumber(tv_haha, 10);

**Comment by china-coder** [comment]
<TextView
            android:id="@+id/tv_haha"
            android:text="haha"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

**Comment by china-coder** [comment]
找到原因了 使用xutils3的时候 就回出现显示问题，原生的findviewbyid是没有问题的
