### ISSUE TITLE
为什么有隐藏方法，但没有隐藏后再显示的方法？

### ISSUE THREAD

**Issue by ChinaFir** [qstumn/BadgeView#38]
如题，总不能每次都new把

**Comment by qq2519157** [comment]
现在好像只有重新把它new出来

**Comment by qstumn** [comment]
当然不是啦，隐藏其实本质上是setBadgeNumber(0) 而已
显示的话你setBadgeNumber或者setBadgeText再次设置内容

**Comment by ChinaFir** [comment]
我一直想着show（）对应hide（）。。。脑筋定式。。。
