### ISSUE TITLE
在自定义 LinearLayout 等组合控件中使用 QBadgeView 怎样才能显示？

### ISSUE THREAD

**Issue by MoveToNext** [qstumn/BadgeView#4]
View inflate = LayoutInflater.from(mContext).inflate(R.layout.base_tipview, this, true);
        Button tipBtn = (Button) inflate.findViewById(R.id.button);
        Badge badge = new QBadgeView(mContext);
        badge.bindTarget(tipBtn);
        badge.setBadgeNumber(5);
        badge.setBadgeBackgroundColor(getResources().getColor(R.color.home_title_color));
        badge.setBadgeGravity(Gravity.END | Gravity.TOP);
不显示 QBadgeView

**Comment by qstumn** [comment]
你好，我这里使用没有问题，只看你的这段代码不清楚问题出在哪
你可以试下1.0.3版是否能解决你的问题
