### ISSUE TITLE
用的时候在Fragment中使用时bindTarget的View的点击事件不能在Fragment实现OnClickListener里面写，用匿名内部类的方式写就没问题了

### ISSUE THREAD

**Issue by fanguangqiang** [qstumn/BadgeView#40]

**Comment by yaozs** [comment]
同样的问题，在fragment中view只能写匿名点击事件，使用id的点击事件无效

**Comment by imgod1** [comment]
1.1.1没问题 更新到1.1.2遇到这个问题了,简直了...

**Comment by Sky0202** [comment]
这有点奇葩啊   ,, 我也是最近用1.1.2 ,使用 id 设置点击无效,  希望作者尽快看看解决一下

**Comment by ClareChen** [comment]
[https://github.com/qstumn/BadgeView/issues](url)

**Comment by ClareChen** [comment]
[https://github.com/qstumn/BadgeView/issues/44](url)
[https://github.com/qstumn/BadgeView/issues/25](url)
