### ISSUE TITLE
BadgeView的颜色改变不了，比如说我设置的是红色，显示的却不是红色而是其他颜色

### ISSUE THREAD

**Issue by ericacx** [qstumn/BadgeView#41]

**Comment by qq2519157** [comment]
不至于吧，能否贴上代码看看

**Comment by ericacx** [comment]
new QBadgeView(_mActivity)
                .bindTarget(processTvNotZhongjiang)
                .setBadgeGravity(Gravity.TOP | Gravity.END)
                .setBadgePadding(3, true)
                .setGravityOffset(0, 0, true)
                .setBadgeBackgroundColor(R.color.red)
                .setBadgeTextColor(R.color.text_colors_white)
                .setBadgeTextSize(14, true)
                .setOnDragStateChangedListener(new Badge.OnDragStateChangedListener() {
                    @Override
                    public void onDragStateChanged(int dragState, Badge badge, View targetView) {

                    }
                })
                .setBadgeNumber(9);

我设置的是setBadgeBackgroundColor(R.color.red)  但是显示的颜色看起来像是紫色。
我加你QQ了，你同意下，我把运行的截图发你。

**Comment by qq2519157** [comment]
把R.color.red换成getResources().getColor(R.color.red)    那个不是我的QQ哈哈

**Comment by qq2519157** [comment]
你直接写R.color.red放进去的只是颜色的id，而这里需要的显然不是resId

**Comment by ericacx** [comment]
ok ,谢谢大神～

**Comment by ericacx** [comment]
setOnDragStateChangedListener  这个里面是执行什么操作呢？

**Comment by qq2519157** [comment]
qBadgeView.setOnDragStateChangedListener(new Badge.OnDragStateChangedListener() {
            @Override
            public void onDragStateChanged(int i, Badge badge, View view) {
                if (Badge.OnDragStateChangedListener.STATE_SUCCEED == i) {
//                    badge.hide(true);
                    Toast.makeText(getBaseContext(), "清除成功", Toast.LENGTH_SHORT).show();
                }
            }
        });
可以在拖拽的时候进行一些操作，监听后就打开了badge拖拽的开关了，类似于QQ小红点的功能
