### ISSUE TITLE
ImageButton设置gravity为end和top无效

### ISSUE THREAD

**Issue by lw254605953** [qstumn/BadgeView#42]
RT，target为ImageButton，style为ActionButton放到了顶部导航栏，设置gravity为Gravity.END | Gravity.TOP，小红点始终位于右侧中间位置，而不是右上角，新手求解答~

**Comment by pgpgfu** [comment]
我也遇到同样的问题   设置Gravity为Gravity.END | Gravity.TOP或者Gravity为Gravity.END | Gravity.TOP，小红点始终位于右侧中间位置，而不是右上角或者左上角。

**Comment by qstumn** [comment]
https://github.com/qstumn/BadgeView/issues/22
