### ISSUE TITLE
setid()的疑问！？

### ISSUE THREAD

**Issue by iamlfc** [qstumn/BadgeView#44]
QBadgeView --> lien 157   这个地方 为什么是targetView.setId(View.NO_ID); 而不是用  targetView.setId(targetView.getId()); 这样不是设置了 新view的id和原始的一样了吗？  应该就可以解决点击事件的问题了吧？

**Comment by five-And** [comment]
哈哈, 跟我想的一样, 我就是这样解决点击事件的:
楼主是给原有控件之外又包了一成, 他担心不复制ID 会照成布局错乱, 而没有考虑到target 的id 会有些事件绑定.  其实子布局和父布局 是可以设置成一个id 的, 两全奇美, 问题都解决了

**Comment by ClareChen** [comment]
同，1.1.1版本并没有修改targetView的ID，而1.1.2版本突然把targetView的ID置空，搞得点击事件响应不了。。。
查了半天原因，不清楚作者这样修改的目的是什么？ @qstumn

**Comment by qstumn** [comment]
https://github.com/qstumn/BadgeView/issues/25
