### ISSUE TITLE
RadioButton使用异常

### ISSUE THREAD

**Issue by likealeodog** [qstumn/BadgeView#5]
new QBadgeView(this).bindTarget(findViewById(R.id.home_rb_online)).setBadgeNumber(bytesList.size());
这个id指向的是我的radiobutton，然后我还有一个地方Radiogroup设置的有监听，然后，一旦我在这里绑定了这个控件，那边的监听就无效了，感觉应该是点击事件被拦截了。难道这种组合按钮还需要单独去获取再设置红点的显示与否吗？

**Comment by qstumn** [comment]
很抱歉，暂不支持绑定RadioButton，QBadgeView和TargetView绑定是采用的换掉TargetView的Parent实现的，RadioButton的Parent必须是RadioGroup，一旦换掉就会出现你描述的情况了

**Comment by likealeodog** [comment]
嗯 我发现其他几个红点组件也有这种情况 不过他们的解决方法是在上层去用一个按钮覆盖在目标view上 治标不治本 而且也不优雅

**Comment by qstumn** [comment]
是，现在这种绑定红点的思路有这样的局限性，如果您找到更好的方法并愿意分享希望到时能告诉我

**Comment by likealeodog** [comment]
嗯 我也看了那个badgeView的源码 确实一般的思路都是去创建一个frameLayout来做替换实现的 利用该布局的重叠性在外层覆盖一个textview 但是容器类型也被替换了 要想解决肯定是在不替换原容器的情况下去显示它 0.0具体我就不知道了

**Comment by cv0cv0** [comment]
不知道qq和微信有没有解决。

**Comment by qstumn** [comment]
QQ和微信有在RadioButton上使用Badge的设计么？ (。﹏。*)
