### ISSUE TITLE
希望增加设置初始半径参数的接口

### ISSUE THREAD

**Issue by Luolc** [qstumn/BadgeView#9]
目前默认的Badge在很多场景下显得有些大了。
刚刚大概看了眼源码，是不是增加一个mDefalutRadius的set接口就可以了呢？没有太仔细看，总之感觉7dp确实大了点。

另，代码风格很赞！

**Comment by qstumn** [comment]
你说的mDefalutRadius具体是指哪个数值？在源码里唯一写死的7dp的地方是在拖拽过程中，拖拽原始位置的初始圆半径，这个会随着拖的距离增加而变得越来越小直到断开，你是觉得这个数值太大了么？

**Comment by Luolc** [comment]
就是感觉目前的圆点有点大了。期望有像微信新消息那种大小的。现在有设置大小的接口嘛？我目前没发现嗯~

**Comment by qstumn** [comment]
Badge的大小是由内部的文字大小+内边距组成的，对应 setBadgeText和setBadgePadding，你可以适当降低其中一个或者两个都调低
如果你是指没有文字的dot，它的大小就只受内边距控制

**Comment by Luolc** [comment]
哦了解，谢谢啦~ 如果可以调的话就没问题啦~ 这个issue可以关了~

**Comment by qstumn** [comment]
你可以下载demo操作试试看，所有的设置参数demo中都有例子，readme里也有方法说明

**Comment by Luolc** [comment]
了解~ demo刚clone的时候没有对应的build tool就没跑~ 待会试一下
